#ifndef MONITORPLUGIN_GLOBAL_H
#define MONITORPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MONITORPLUGIN_LIBRARY)
#  define MONITORPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MONITORPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MONITORPLUGIN_GLOBAL_H
