#ifndef UPLOADPLUGIN_GLOBAL_H
#define UPLOADPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UPLOADPLUGIN_LIBRARY)
#  define UPLOADPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UPLOADPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UPLOADPLUGIN_GLOBAL_H
