#ifndef PARSEPLUGIN_GLOBAL_H
#define PARSEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PARSEPLUGIN_LIBRARY)
#  define PARSEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PARSEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PARSEPLUGIN_GLOBAL_H
